apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-express
  labels:
    app: tomcat-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-express
  template:
    metadata:
      labels:
        app: tomcat-express
    spec:
      containers:
      - name: tomcat-express
        image: suresh1993/samplewebapp:latest
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-express-service
spec:
  selector:
    app: tomcat-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30000
